IMG: 'data/q2/q2b.png'

N_HOMOGRAPHIES: 3

COLORS:
- [219, 62, 177]
- [68, 214, 44]
- [210, 39, 48]
- [255, 173, 0]

ORIG_POINTS:
- [[0, 0], [1, 0], [1, 1], [0, 1]]
- [[0, 0], [1, 0], [1, 1], [0, 1]]
- [[0, 0], [1, 0], [1, 1], [0, 1]]