NAME: 'chair'

IMGS:
- 'data/q1a/chair/image_1.jpg'
- 'data/q1a/chair/image_2.jpg'

CORRESPONDENCES: 'data/q1a/chair/chair_corresp_raw.npz'
CORRESPONDENCES_RAW: 'data/q1a/chair/chair_corresp_raw.npz'

INTRINSICS: 'data/q1a/chair/intrinsic_matrices_chair.npz'

N_ANNOTATION_POINTS: 2

COLORS:
- [255, 0, 0]
- [0, 255, 0]
