NAME: 'toybus'

IMGS:
- 'data/q1b/toybus/image_1.jpg'
- 'data/q1b/toybus/image_2.jpg'

CORRESPONDENCES: 'data/q1b/toybus/toybus_7_point_corresp.npz'
CORRESPONDENCES_RAW: 'data/q1b/toybus/toybus_corresp_raw.npz'

INTRINSICS: 'data/q1b/toybus/intrinsic_matrices_toybus.npz'

N_ANNOTATION_POINTS: 2

COLORS:
- [255, 0, 0]
- [0, 255, 0]